#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		echo '';
	else
		if [ "$remote_sha" = $z40 ]
		then
			# New branch, examine all commits
			remote_sha=`git rev-list --boundary $local_ref...origin/main | grep "^-" | cut -c2- | tail -n1`
			npx --no -- commitlint --from $remote_sha --to $local_sha
		else
			# Update to existing branch, examine new commits
			npx --no -- commitlint --from $remote_sha --to $local_sha
		fi
	fi
done

exit 0
npx --no -- commitlint --from
